### ISSUE TITLE
Not setting Trigger.EndBoundary throws exception in Win7

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#101]
Code below, compiled either as .NET 3.0 or .NET 3.5, fails to execute in Windows 7 Professional SP1 64-bit. Works without problems in Windows XP computers.
 
using (TaskService taskService = new TaskService())
{
    TaskDefinition task = taskService.NewTask();
 
    Trigger trigger = new DailyTrigger(1);
    trigger.Repetition.Duration = new TimeSpan(24, 0, 0);
 
    task.Triggers.Add(trigger);
    task.Actions.Add(new ExecAction("notepad.exe", String.Empty, @"C:\Windows"));
 
    // Ensures the task is marked with 'delete the task if it is not scheduled to run again'
    task.Settings.DeleteExpiredTaskAfter = new TimeSpan(0, 1, 0);
 
    // We want that the task is executed under a specific user even when the user is not logged in
    taskService.RootFolder.RegisterTaskDefinition("Test Task", task, TaskCreation.CreateOrUpdate, "username", "password", TaskLogonType.Password, null);
}
 
The following exception is thrown:
 
Unhandled Exception: System.Runtime.InteropServices.COMException (0x80041319): (41,4):EndBoundary:
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)
   at VolvoIt.Waf.Tools.CreateScheduledTasks.Program.Main(String[] args)

Originally posted: 2011-06-13T13:16:45

**Comment by dahall** [comment]
Under V2 &#40;Vista and higher&#41;, whenever you assign a value to DeleteExpiredTaskAfter you must also assign a value to EndBoundary. I also noticed your use of Repetition.Duration without specifying Repetition.Interval. The DailyTrigger will already repeat each day based on the specified DaysInterval. I think that line may be extraneous. See dicussion entry for working code.

Originally posted: 2011-06-13T14:32:25
