### ISSUE TITLE
There is no running instance of the task. (Exception from HRESULT: 0x8004130B)

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#108]
Hello,
 
When making a call to GetRunningTasks in Microsoft.Win32.TaskScheduler.TaskService I sometimes receive the following exception: "There is no running instance of the task. (Exception from HRESULT: 0x8004130B)".
 
Here is the call stack:
 
                   at Microsoft.Win32.TaskScheduler.V2Interop.IRunningTask.get_Path()
   at Microsoft.Win32.TaskScheduler.RunningTaskCollection.RunningTaskEnumerator.get_Current() in D:\Visual Studio 2008\Projects\NASP.Common\NASP.Common.TaskService\TaskCollection.cs:line 353
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 
It apppears to be throwing the exception in the property:
 
public RunningTask Current
			{
				get
				{
					V2Interop.IRunningTask irt = (V2Interop.IRunningTask)iEnum.Current;
					V2Interop.IRegisteredTask task = TaskService.GetTask(v2Svc, irt.Path);
					if (task == null) return null;
					return new RunningTask(svc, task, irt);
				}
			}
 
specifically at "V2Interop.IRegisteredTask task = TaskService.GetTask(v2Svc, irt.Path);"
 
Am I doing something wrong?
 
Thanks,
Michael DePouw

Originally posted: 2011-12-09T13:14:42

**Comment by dahall** [comment]
What is happening is that between the enumerating of all the running tasks and the request for a specific task, that task must finish running. I will look at the code to see what I can do to make sure the enumerator accounts for tasks spinning up and down. For now, the work around is to put a try/catch block around the call to get each running task so it can fail gracefully.

Originally posted: 2011-12-09T14:13:29

**Comment by dahall** [comment]
Thanks for the quick and knowledgeable response.  I'll implement the work around.

Thanks,
MD

Originally posted: 2011-12-10T10:32:23

**Comment by dahall** [comment]
Originally posted: 2012-01-12T11:22:51
