### ISSUE TITLE
The function attempted to use a name that is reserved for use by another transaction. (Exception from HRESULT: 0x80071A90)

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#109]
I received the following exception when calling GetRunningTasks:
 
"The function attempted to use a name that is reserved for use by another transaction. (Exception from HRESULT: 0x80071A90)"
 
Here is the call stack:
at Microsoft.Win32.TaskScheduler.V2Interop.TaskSchedulerClass.GetRunningTasks(Int32 flags)
at Microsoft.Win32.TaskScheduler.TaskService.GetRunningTasks(Boolean includeHidden) in TaskService.cs:line 113
 
Section of code (line 113 is the return statement):
```
public RunningTaskCollection GetRunningTasks(bool includeHidden)
{
    return v2 ? new RunningTaskCollection(this, v2TaskService.GetRunningTasks(includeHidden ? 1 : 0)) : new RunningTaskCollection(this);
}
```
The next time I called GetRunningTasks it succeeded but I'm concerned this exception is going to happen again.
 
Thanks,
Michael DePouw

Originally posted: 2011-12-10T15:16:58

**Comment by dahall** [comment]
I have never heard of this error nor was I able to find any reference to it online related to the Task Scheduler. Please let me know if you ever see this error again as it has never been reported here.

Originally posted: 2011-12-10T23:48:32

**Comment by dahall** [comment]
Ok, thanks dahall.  And thanks for the quick response.

MD

Originally posted: 2011-12-11T15:10:51

**Comment by dahall** [comment]
I think it is related to me using the Display All Running Tasks via the MMC concurrently.

I just had it happen to me again.  When it happened I had the Display All Running Tasks form from the Microsoft Task Schedule MMC open and I was repeated clicking refresh.

I ran the task again and didn't open the form from the MMC and it didn't happen.  This doesn't prove it was the culprit but it is a piece of evidence.

Originally posted: 2011-12-11T20:32:57

**Comment by dahall** [comment]
I ran this test with MMC up and found the same error. I have traced the problem back to the Microsoft native library. I will be posting the issue as a concurrency problem to Microsoft.

Originally posted: 2013-03-11T13:18:18

**Comment by dahall** [comment]
Thanks @dahall!  That's great news.  Thanks for following up on the matter.

Regards,
Mike DePouw

Originally posted: 2013-03-11T13:57:45

**Comment by dahall** [comment]
Reported to Microsoft.

Originally posted: 2013-03-11T13:18:31
