### ISSUE TITLE
Can't edit existing tasks, Exception thrown

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#114]
If I try to edit a trigger (let's say the time) of an existing scheduled task using this code:
 
      using (var taskEditDialog = new TaskEditDialog(_tlv.Tasks[_tlv.SelectedIndex], true, false))
      {
        taskEditDialog.RegisterTaskOnAccept = true;
 
        if (taskEditDialog.ShowDialog() == DialogResult.OK)
        {
          var t = taskEditDialog.Task;
        }
      }
 
I get the following error:
 
System.NullReferenceException was unhandled
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Win32.TaskScheduler
  StackTrace:
       at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)
       at Microsoft.Win32.TaskScheduler.TaskEditDialog.okBtn_Click(Object sender, EventArgs e)
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.RunDialog(Form form)
       at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
       at System.Windows.Forms.Form.ShowDialog()
       at TaskSchedulerTest.Form1.EditTask() in C:\Projects\Temp\TaskSchedulerTest\TaskSchedulerTest\Form1.cs:line 109
       at TaskSchedulerTest.Form1.btnEdit_Click(Object sender, EventArgs e) in C:\Projects\Temp\TaskSchedulerTest\TaskSchedulerTest\Form1.cs:line 95
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at TaskSchedulerTest.Program.Main() in C:\Projects\Temp\TaskSchedulerTest\TaskSchedulerTest\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

Originally posted: 2012-03-02T12:57:49

**Comment by dahall** [comment]
First, the third parameter of the constructor for TaskEditDialog sets the RegisterTaskOnAccept property. You could eliminate setting the property separately by simply setting the constructor's parameter to True.

Secondly, I have run this code on both Win7 and XP without any problems. I would check to make sure the value of _tlv.Tasks[_tlv.SelectedIndex] is returning a valid task and that the Task.Definition.Principal does not specify LogonType that requires a password. If so, then the task cannot be automatically re-registered and needs to be done manually after getting the TaskDefinition back from the TaskEditDialog.

Originally posted: 2012-03-02T17:57:27

**Comment by dahall** [comment]
OK, I have update the code:
  using (var taskEditDialog = new TaskEditDialog(_tlv.Tasks[_tlv.SelectedIndex], true, true))
      {
        if (taskEditDialog.ShowDialog() == DialogResult.OK)
        {
          var t = taskEditDialog.Task;
        }
      }

No change in behavior, same exception.
The value if the selected object is of course set, because the edit dialog show the actual Task. As soon as I edit the Trigger Time and click Ok->Ok it crashes. The scheduled task is set to run with my own account, the very same I run my code with.

BTW, I just noticed that the "Run Times" tab in the edit dialog says:
Unable to show the run times for this task.
Error: System.NullReferenceException: Onject reference not set to an instance of an object. at Microsoft.Win32.TaskScheduler.TaskFolder.REgisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)



Originally posted: 2012-03-03T10:56:10

**Comment by dahall** [comment]
A small update, I don't even have to change anything. Just open the TaskEdit dialog and  click OK, I get the same Exception.

Originally posted: 2012-03-03T11:02:42

**Comment by dahall** [comment]
I have attached a simple test program that crashes for me all the time. One thing to note is that is uses folders. What am I doing wrong that causes it to crash?


Originally posted: 2012-03-03T11:07:50

**Comment by dahall** [comment]
I think your problem has something to do with how you use the 'using' statement all over and the objects are disposed before they can re-register the task and the incorrect use of the HighestSupportVersion test for systems later than XP. I have uploaded a new Form1.cs file with much simpler code using class properties that does not throw the exception. Please try and let me know if your problem still persists.

Originally posted: 2012-03-04T00:04:59

**Comment by dahall** [comment]
Great, that seems to work better. But How can I persist the changes back to the TaskService?
Edit works on the Task I have given to the TaskEditDialog, but how to save it back?

Originally posted: 2012-03-04T14:50:27

**Comment by dahall** [comment]
Once you have a task, passing it to the TaskEditDialog with the RegisterTaskOnAccept set to true or through the third parameter on the constructor, will post the changes back to TaskService. If you need to make changes to a task outside of the editor you can call the RegisterChanges method on the task.

Originally posted: 2012-03-04T20:07:18

**Comment by dahall** [comment]
Originally posted: 2012-03-04T20:08:22
