### ISSUE TITLE
Exception on MonthlyDOWTrigger added in Windows XP

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#119]
Hello,
 
I've found an exception when I add MonthlyDOWTrigger in task definition and set the DaysOfWeek property :
 
Value does not fall within the expected range.
   at Microsoft.Win32.TaskScheduler.V1Interop.ITaskTrigger.SetTrigger(TaskTrigger& Trigger)
   at Microsoft.Win32.TaskScheduler.Trigger.SetV1TriggerData() in C:\Users\***\Documents\Visual Studio 2010\Projects\MonthlyDOWTriggerExceptionDemo\TaskService\Trigger.cs:line 646
   at Microsoft.Win32.TaskScheduler.MonthlyDOWTrigger.set_DaysOfWeek(DaysOfTheWeek value) in C:\Users\***\Documents\Visual Studio 2010\Projects\MonthlyDOWTriggerExceptionDemo\TaskService\Trigger.cs:line 1280
   at MonthlyDOWTriggerExceptionDemo.Program.Main(String[] args) in c:\users\***\documents\visual studio 2010\Projects\MonthlyDOWTriggerExceptionDemo\MonthlyDOWTriggerExceptionDemo\Program.cs:line 34
 
 
I join the test program sources reproduce that bug if can help you.
 
Thank you

Originally posted: 2012-05-02T07:01:26

**Comment by dahall** [comment]
Thank you for finding this relatively obscure bug. It has been corrected in source release 77874. The use of the Triggers.AddNew method is rarely used given that there are contructors that simplify the settings. For example, I would typically expect to see your code look more like this single line:

MonthlyDOWTrigger mdTrigger = (MonthlyDOWTrigger)td.Triggers.Add(new MonthlyDOWTrigger(DaysOfTheWeek.Monday, MonthsOfTheYear.AllMonths, WhichWeek.AllWeeks) { StartBoundary = DateTime.Now.AddMinutes(1) });

Originally posted: 2012-05-03T10:30:19

**Comment by dahall** [comment]
Thank you for your answer and your correction. I integrate that new release.

And thank you for your advices

Originally posted: 2012-05-04T06:44:28

**Comment by dahall** [comment]
Corrected in source release 77874

Originally posted: 2012-05-03T10:30:53
