### ISSUE TITLE
RegisterTaskDefinition() with TaskCreation.ValidateOnly parameter throws NullReferenceException

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#144]
I noticed a strange error today when attempting to use the RegisterTaskDefinition() method from the TaskFolder class.  If I use this overload:

```
RegisterTaskDefinition(string path, TaskDefinition definition, TaskCreation creationOption, string UserName)
```

Then I get a NullReferenceException.  The portion of the stacktrace that shows where the problem is as follows:

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Win32.TaskScheduler
  StackTrace:
       at Microsoft.Win32.TaskScheduler.Task.GetV2Definition(TaskService svc, IRegisteredTask iTask, Boolean throwError)
       at Microsoft.Win32.TaskScheduler.Task.CreateTask(TaskService svc, IRegisteredTask iTask, Boolean throwError)
       at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)
       at MYAPPLIATION.GUI.SchedulingManager.addTaskButton_Click(Object sender, EventArgs e) in MYAPPLICATION\GUI\SchedulingManager.cs:line 175
```

If I remove the TaskCreation enum option and the username to use the overload that is only Name & Definition, then there are no issues.  The option that I'm using is TaskCreation.ValidateOnly option since I  don't want to actually register the task just yet.

Originally posted: 2014-04-22T14:58:58

**Comment by dahall** [comment]
Thanks for taking a look!  I looked at the diff to take a look at the changes in both documentation & code, but am a little bit confused.  Are you saying if using ValidateOnly it returns null if it DOES validate successfully, or if it fails to validate?  I'm hoping it's the latter, but just want to be 100% sure.

Originally posted: 2014-04-23T09:56:58

**Comment by dahall** [comment]
If you are using the library, it is very, very hard to create an invalid TaskDefinition, so I'm not sure why you would need to validate anyway. There is a rich validation method (Validate) on the TaskDefinition class that will tell you exactly what your issues are.

Anyway, to answer your question, if there is a validation problem when registering using the ValidateOnly flag, it will throw an exception. If there is NOT a validation problem, then it will return 'null'. It cannot return a Task because one is not created.

Originally posted: 2014-04-23T10:51:30

**Comment by dahall** [comment]
Thanks for the info.  I actually didn't really want to validate, I just was looking for a method to create a task object to send to the TaskSchedulerEditor UI that was not registered, but 99% of it is already pre-populated.  I then wanted to use the definition from the TaskSchedulerEditor as the one that actually gets registered.  Now that I'm typing this out I just thought of a much better way to handle this anyway, but I'm glad that's fixed either way!

Originally posted: 2014-04-23T11:39:51

**Comment by dahall** [comment]
You can do that by passing the TaskDefinition to the TaskEditDialog instead of the Task, setting RegisterTaskOnAccept to false and then handling the registration yourself after the user edits the task.

Originally posted: 2014-04-23T13:25:59

**Comment by dahall** [comment]
Fixed in latest code drop

Originally posted: 2014-04-22T20:58:51
