### ISSUE TITLE
System.IO.FileNotFoundException V1Interop.ITaskScheduler.Activate

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#153]
Can you help me, I just got this error on Windows XP Pro (SP3)

System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Microsoft.Win32.TaskScheduler.V1Interop.ITaskScheduler.Activate(String Name, Guid& riid)
   at Microsoft.Win32.TaskScheduler.TaskService.GetTask(ITaskScheduler iSvc, String name)
   at Microsoft.Win32.TaskScheduler.TaskService.GetTask(String taskPath)
   at SmartShare.schedulemanager.ScheduleSleep(Int32 idleSetting)
   at SmartShare.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)

Originally posted: 2014-12-08T23:00:02

**Comment by dahall** [comment]
What is the name of your task? Win XP treats tasks as files but it manipulates the filename. This error often occurs when the name of task, once manipulated, gets into a cycle where the manipulation conflicts with the name. It can also occur when the user account used to construct the TaskService instance does not have permissions on the C:\Windows\Tasks folder.

Originally posted: 2014-12-09T08:19:24

**Comment by dahall** [comment]
Were you able to resolve your issue?

Originally posted: 2015-01-26T09:43:50

**Comment by dahall** [comment]
Unknown resolution

Originally posted: 2015-02-17T09:46:05
