### ISSUE TITLE
Recently we got AccessViolationException

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#155]
Hi! Recently we've got the following exception. It happened one time and we cannot reproduce it.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.Win32.TaskScheduler.V2Interop.IRegisteredTask.get_Definition()
   at Microsoft.Win32.TaskScheduler.Task.GetV2Definition(TaskService svc, IRegisteredTask iTask, Boolean throwError)
   at Microsoft.Win32.TaskScheduler.Task.get_Definition()

We run our WPF application on Win7, .Net 3.5.

Originally posted: 2015-02-19T07:13:11

**Comment by dahall** [comment]
I've just gone through the code and cannot find a place where there is even a memory allocation or deallocation related to that code. The particular line is even within a "try" clause. My only guess (and sorry to push this off but I really can't see anything that would lead to that exception) is that it has something to do with Microsoft's internal library. That particular method call (IRegisteredTask.get_Definition) is a call into one of Microsoft's COM objects. It would not be surprising given the complexity of that result (ITaskDefinition) and I could see a corner case in creating the return object. I'll leave this issue open for a few months in case you are able to narrow the problem down though.

Originally posted: 2015-02-19T09:21:28

**Comment by dahall** [comment]
Originally posted: 2015-07-09T19:05:36
