### ISSUE TITLE
NullReferenceException when display Run Times in TaskEditDialog

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#178]
When I try displaying the schedule for the an __existing__ task, I see the following error in the Run Times tab.

Unable to show the run times for this task.
Error: System.NullReferenceException: Object references not set to an instance of an object.
   at Microsoft.Win32.TaskScheduler.TaskService.NewTask()
   at Microsoft.Win32.TaskScheduler.TaskPropertiesControl.runTimesTab_Enter(Object sender, EventArgs e)

If I click ok, Windows display a Quit, Continue, Ignore dialog box and nothing gets saved.

Note that is only happening when I try to modify an existing task. If I create a new task, the RunTimes tab gets filled correctly.

Originally posted: 2015-12-09T12:28:45

**Comment by dahall** [comment]
In addition to my last message, I get the following stack trace when I click OK in the dialog box.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition)
   at Microsoft.Win32.TaskScheduler.Task.RegisterChanges()
   at Microsoft.Win32.TaskScheduler.TaskEditDialog.okBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)



Originally posted: 2015-12-09T13:54:08

**Comment by dahall** [comment]
Ok, I found the problem. It was a false alarm but a good lesson to learn.

My original code was:

```
Task myTask;
using (TaskService ts = new TaskService()){
     myTask = SearchForMyTask(ts); //Returns the one I need.
 }
// Some code here 
//Eventually

using (TaskEditDialog editorForm = new TaskEditDialog(myTask)) {           
    editorForm.ShowDialog(this);
}

//I was running into this error because my original TaskService ts was garbage collected.
```
The actual problem was 

__Task.RegisterChanges__() method, which calls __CreateTask__ method, which then calls __GetV2Definition__. The GetV2Definition does not check if the svc variable is valid and as a result a NullReferenceException is raised.

Solution was to move the TaskService to higher scope






Originally posted: 2015-12-09T14:29:43

**Comment by dahall** [comment]
Originally posted: 2015-12-14T15:58:38
