### ISSUE TITLE
In Task Editor, Marshal.ReleaseComObject throws an ArgumentException when called on a .NET COM class

### ISSUE THREAD

**Issue by Gwindalmir** [dahall/TaskScheduler#27]
I created a COM server in C#, but when I try to select my COM class as a custom action in the Task editor, I get an exception:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=The object's type must be __ComObject or derived from __ComObject.
Parameter name: o
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)
   at Microsoft.Win32.TaskScheduler.ComObjectSelectionDialog.SupportsInterface(Guid clsid, Guid iGuid)
   at Microsoft.Win32.TaskScheduler.ComObjectSelectionDialog.listView1_ItemSelectionChanged(Object sender, ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Here's the class I created:
```
using Microsoft.Win32.TaskScheduler;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace Scheduler
{
    [ComVisible(true)]  // This is mandatory.
    [Guid("4945B34B-1B63-4a58-B5FE-9627FEFAEA9D")]
    [InterfaceType(ComInterfaceType.InterfaceIsDual)]
    public interface ITaskRunner
    {
    }

    [Guid("FA40C9BB-410C-46D2-AEC9-8F7D952B3E91")]
    [ClassInterface(ClassInterfaceType.AutoDispatch)]
    [ComVisible(true)]
    public class TaskRunner : ITaskHandler
    {
        public void Start(object pHandlerServices, string data)
        {
            throw new NotImplementedException();
        }

        public void Stop(out int pRetCode)
        {
            throw new NotImplementedException();
        }

        public void Pause()
        {
            throw new NotImplementedException();
        }

        public void Resume()
        {
            throw new NotImplementedException();
        }
    }
}
```

If I remove the Marshal.ReleaseComObject call in SupportsInterface, I can select it fine.
I noticed this with other COM servers on my machine (when randomly selecting), not just mine.

**Comment by dahall** [comment]
Using your suggestion, this item has been fixed and committed and will be in the next release (likely 2.6.4).
