### ISSUE TITLE
native library (1.3) does not support the ".NET Framework NGEN v4.0.30319" task (1.4/1.4)

### ISSUE THREAD

**Issue by lancehilliard** [dahall/TaskScheduler#45]
I've created a Console Application which queries 90 remote hosts to list their scheduled tasks. After listing the scheduled tasks of multiple hosts successfully, the wrapper throws the following error on multiple hosts:

> The current version of the native library (1.3) does not support the original or minimum version of the ".NET Framework NGEN v4.0.30319" task (1.4/1.4)

Here's the stacktrace:

>    at Microsoft.Win32.TaskScheduler.Task.GetV2Definition(TaskService svc, IRegisteredTask iTask, Boolean throwError)
>    at Microsoft.Win32.TaskScheduler.Task.get_Definition()
>    at ScheduledTasks.ConsoleApp.Program.<>c.<EnumFolderTasks>g__IsRelevant|2_0(Task x) in C:\path\to\ScheduledTasks.ConsoleApp\Program.cs:line 59

The "line 59" cited interrogates the `Definition` property of the `Microsoft.Win32.TaskScheduler.Task` object. Trying to access that `Definition` property seems to be what's throwing the error? I can provide the full code if that helps. In case it's relevant, the Console Application is running in Windows 7, and all of these queried hosts (those successful and those throwing errors) are running more modern operating systems.

What does this error mean? What can I change to be able to reliably use this `Definition` property?

**Comment by lancehilliard** [comment]
Here's the full code I'm using, with TaskScheduler 2.7.2 installed from NuGet. Note the location of the following comment in the shared code:

 // "line 59" cited in stacktrace above

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using Microsoft.Win32.TaskScheduler;

namespace ScheduledTasks.ConsoleApp {
    internal class Program {
        private static readonly string Domain = "contoso";
        private static readonly string RootPath = @"\";

        private static void Main() {
            var serverNames = new List<string>{"host1", "host2", "host3", "etc"}.OrderBy(x=>x).ToList();
            Output($"Running on {Environment.MachineName}. Querying {serverNames.Count} servers:");
            Output($"{string.Join(", ", serverNames)}");
            Output();
            EnumAllTasks(serverNames);
        }

        private static void EnumAllTasks(IEnumerable<string> serverNames) {
            foreach (var serverName in serverNames) {
                try {
                    using (var ts = new TaskService(serverName)) {
                        EnumFolderTasks(ts.RootFolder);
                    }
                }
                catch (Exception e) {
                    var errorMessage = $"{serverName} - Exception: {e.Message}";
                    Output(errorMessage, true);
                    Output(isError: true);
                }
            }
        }

        private static void EnumFolderTasks(TaskFolder taskFolder) {
            bool IsRelevant(Task x) {
                var isEnabled = x.Enabled;
                var isInRootFolder = x.Folder.Path.Equals(RootPath);
                var hasDomainUser = x.Definition.Principal.UserId?.Contains(Domain) ?? false; // "line 59" cited in stacktrace above
                var hasExecActions = x.Definition.Actions.OfType<ExecAction>().Any();
                return isEnabled && isInRootFolder && hasDomainUser && hasExecActions;
            }
            foreach (var task in taskFolder.AllTasks.Where(IsRelevant)) { Print(task); }
            foreach (var subFolder in taskFolder.SubFolders) { EnumFolderTasks(subFolder); }
        }

        private static void Print(Task t) {
            Output($@"\\{t.TaskService.TargetServer ?? Environment.MachineName}{t.Path}\{t.Name}:");
            foreach (var execAction in t.Definition.Actions.OfType<ExecAction>()) {
                Output($"Path: {execAction.Path}");
                Output($"Args: {execAction.Arguments}");
            }
            foreach (var trigger in t.Definition.Triggers) {
                var triggerDescriptor = "When: ";
                if (trigger is WeeklyTrigger weeklyTrigger) {
                    triggerDescriptor = $"{triggerDescriptor}{weeklyTrigger.DaysOfWeek} ";
                }
                triggerDescriptor = $"{triggerDescriptor}@ {trigger.StartBoundary.ToShortTimeString()}";
                if (trigger.Repetition.IsSet()) {
                    triggerDescriptor = $"{triggerDescriptor} (Interval: {trigger.Repetition.Interval}; Duration: {trigger.Repetition.Duration})";
                }
                Output(triggerDescriptor);
            }
            Output($"Service Account: {t.Definition.Principal.UserId}");
            Output("Reason: ");
            Output();
        }

        private static void Output(string message = null, bool isError = false) {
            var timeDescriptor = Process.GetCurrentProcess().StartTime.ToString("yyyyMMddHHmmss");
            var categoryDescriptor = isError ? "errors" : "info";
            File.AppendAllText($"{timeDescriptor}-{categoryDescriptor}.txt", $"{message}{Environment.NewLine}");
            Console.WriteLine(message);
        }
    }
}
```

**Comment by lancehilliard** [comment]
I resolved this by running the same code from a Windows Server 2012 R2 machine. All of my hosts query successfully without error. Please close this issue whenever it suits you.

**Comment by dahall** [comment]
You figured it out. An down-level machine with an older version of the native Task Scheduler library will have problems when accessing up-level tasks. Unfortunately this is a native library problem and this wrapper library is unable to cover it up.
