### ISSUE TITLE
Task creation issue and login issue 

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#652]
What is happening and I don't understand is when the user installs my app it doesn't use the user name but goes to "System" and with the settings "Run whether user is logged on or not."  
  
When I delete the task using your code which works and I re create the task using the code below It then create the task using my Login name instead of System and is set to Run only when user is logged on.   
  
  
The task is created at first run in my program.   
I don't understand why this is happening.   
  
  
Here is the code that I am using. is below  

    Using ts As New TaskService
    
                ' Create a new task definition and assign properties
                Dim td As TaskDefinition = ts.NewTask
                td.RegistrationInfo.Description = &quot;Test Startup&quot;
                'Create trigger that fires 1 minutes after the system starts.
                td.Principal.UserId = Environment.UserName
                td.Principal.LogonType = TaskLogonType.InteractiveToken
                td.Triggers.Add(New LogonTrigger())
                td.Actions.Add(New ExecAction(&quot;C:\test.exe&quot;)
                td.Principal.RunLevel = TaskRunLevel.Highest
                td.Settings.Compatibility = TaskCompatibility.V2_1
                ts.RootFolder.RegisterTaskDefinition(&quot;test app&quot;, td)
    
            End Using

thank you for your help and support   
Brock   

Originally posted: 2015-12-23T00:07:36

**Comment by dahall** [comment]
also forgot to mention I'm running windows 10 Pro 64 bit and the latest version for you DLL I believe its 2,5,8 I think.  


Originally posted: 2015-12-23T06:40:59

**Comment by dahall** [comment]
When no user information is provided to the `RegisterTaskDefinition` method, it first looks to those provided to the `Principal` property and then uses the credentials of those provided to the `TaskService` constructor. It cannot give privileges higher than those provided to the `TaskService` instance. When no user information is provided to the `TaskService` constructor, it uses those of the executing assembly. Unless you have specifically setup a manifest file for your executable or run it using "Run as Administrator", then UAT will step in and reduce the account privileges dramatically.  
  
I believe the following will correct your code:  

&#39; Create a new task definition and assign properties
    Dim td As TaskDefinition = TaskService.Instance.NewTask
    td.RegistrationInfo.Description = &quot;Test Startup&quot;
    &#39;Create trigger that fires 1 minutes after the system starts.
    Dim lt As LogonTrigger = New LogonTrigger()
    lt.Delay = TimeSpan.FromMinutes(1)
    &#39;Set trigger to only fire for this account so elevated permissions are not needed
    lt.UserId = Environment.UserName
    td.Triggers.Add(lt)
    &#39;The Add method assumes an ExecAction when the parameters are strings
    td.Actions.Add(&quot;C:\test.exe&quot;)
    td.Principal.RunLevel = TaskRunLevel.Highest
    td.Settings.Compatibility = TaskCompatibility.V2_1
    TaskService.Instance.RootFolder.RegisterTaskDefinition(&quot;test app&quot;, td)


Originally posted: 2015-12-23T09:24:35

**Comment by dahall** [comment]
What does this Exception mean ?   
  
(17,8):userId:  
  
I'm getting it at creation of a new task.   


Originally posted: 2015-12-23T21:30:08

**Comment by dahall** [comment]
Here is the exception text. I've even tried my old  code and still get the error after my program is installed.   


    System.Runtime.InteropServices.COMException (0x80070534): (17,8):UserId:
       at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
       at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)
       at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition)



Originally posted: 2015-12-24T12:11:04

**Comment by dahall** [comment]
My guess is that there is something wrong with the format of the supplied LogonTrigger.UserId property value. The following is information from the Microsoft support page:  


> The identifier of the user. For example, "MyDomain\MyName" or for a local account, "Administrator".   
> This property can be in one of the following formats:   
> • User name or SID: The task is started when the user logs on to the computer.  
> • Group name or SID string: The task is started when a member of the user group logs on to the computer.  
> • NULL: The task is started when any user logs on to the computer.



Originally posted: 2015-12-24T15:18:52

**Comment by dahall** [comment]
**dahall wrote:**  


> When no user information is provided to the `RegisterTaskDefinition` method, it first looks to those provided to the `Principal` property and then uses the credentials of those provided to the `TaskService` constructor. It cannot give privileges higher than those provided to the `TaskService` instance. When no user information is provided to the `TaskService` constructor, it uses those of the executing assembly. Unless you have specifically setup a manifest file for your executable or run it using "Run as Administrator", then UAT will step in and reduce the account privileges dramatically.  
>   
> I believe the following will correct your code:  
> 
> &#39; Create a new task definition and assign properties
>     Dim td As TaskDefinition = TaskService.Instance.NewTask
>     td.RegistrationInfo.Description = &quot;Test Startup&quot;
>     &#39;Create trigger that fires 1 minutes after the system starts.
>     Dim lt As LogonTrigger = New LogonTrigger()
>     lt.Delay = TimeSpan.FromMinutes(1)
>     &#39;Set trigger to only fire for this account so elevated permissions are not needed
>     lt.UserId = Environment.UserName
>     td.Triggers.Add(lt)
>     &#39;The Add method assumes an ExecAction when the parameters are strings
>     td.Actions.Add(&quot;C:\test.exe&quot;)
>     td.Principal.RunLevel = TaskRunLevel.Highest
>     td.Settings.Compatibility = TaskCompatibility.V2_1
>     TaskService.Instance.RootFolder.RegisterTaskDefinition(&quot;test app&quot;, td)

Hi dahl,   
  
I'm still having the issue Where the task is registering the as System and not the username, I am using the code you supplied but still no go.   
  
When people install the App it asks for UAC prompt so it does install under administrator. but when I check the task it says system. If I restart my app and register the task it works as it should with the username and not SYSTEM.   
  
It seems at install I'm having the issue. I'm using the a manifest file. I'll post it as well for you too see., It just a simple msi installer.   


    &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    &lt;asmv1:assembly manifestVersion=&quot;1.0&quot; xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot; xmlns:asmv1=&quot;urn:schemas-microsoft-com:asm.v1&quot; xmlns:asmv2=&quot;urn:schemas-microsoft-com:asm.v2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
      &lt;assemblyIdentity version=&quot;1.0.0.0&quot; name=&quot;MyApplication.app&quot;/&gt;
      &lt;trustInfo xmlns=&quot;urn:schemas-microsoft-com:asm.v2&quot;&gt;
        &lt;security&gt;
          &lt;requestedPrivileges xmlns=&quot;urn:schemas-microsoft-com:asm.v3&quot;&gt;
            &lt;!-- UAC Manifest Options
                If you want to change the Windows User Account Control level replace the 
                requestedExecutionLevel node with one of the following.
    
            &lt;requestedExecutionLevel  level=&quot;asInvoker&quot; uiAccess=&quot;false&quot; /&gt;
            &lt;requestedExecutionLevel  level=&quot;requireAdministrator&quot; uiAccess=&quot;false&quot; /&gt;
            &lt;requestedExecutionLevel  level=&quot;highestAvailable&quot; uiAccess=&quot;false&quot; /&gt;
    
                Specifying requestedExecutionLevel node will disable file and registry virtualization.
                If you want to utilize File and Registry Virtualization for backward 
                compatibility then delete the requestedExecutionLevel node.
            --&gt;
            &lt;requestedExecutionLevel  level=&quot;highestAvailable&quot; uiAccess=&quot;false&quot; /&gt;
          &lt;/requestedPrivileges&gt;
        &lt;/security&gt;
      &lt;/trustInfo&gt;
      
      &lt;compatibility xmlns=&quot;urn:schemas-microsoft-com:compatibility.v1&quot;&gt;
        &lt;application&gt;
          &lt;!-- A list of all Windows versions that this application is designed to work with. Windows will automatically select the most compatible environment.--&gt;
    
          &lt;!-- If your application is designed to work with Windows 7, uncomment the following supportedOS node--&gt;
          &lt;!--&lt;supportedOS Id=&quot;{35138b9a-5d96-4fbd-8e2d-a2440225f93a}&quot;/&gt;--&gt;
          
        &lt;/application&gt;
      &lt;/compatibility&gt;
      
      &lt;!-- Enable themes for Windows common controls and dialogs (Windows XP and later) --&gt;
      &lt;!-- &lt;dependency&gt;
        &lt;dependentAssembly&gt;
          &lt;assemblyIdentity
              type=&quot;win32&quot;
              name=&quot;Microsoft.Windows.Common-Controls&quot;
              version=&quot;6.0.0.0&quot;
              processorArchitecture=&quot;*&quot;
              publicKeyToken=&quot;6595b64144ccf1df&quot;
              language=&quot;*&quot;
            /&gt;
        &lt;/dependentAssembly&gt;
      &lt;/dependency&gt;--&gt;
    
    &lt;/asmv1:assembly&gt;
    
    

thank you for your help  
Brock  


Originally posted: 2016-03-22T20:02:39

**Comment by dahall** [comment]
Do you want the task to run when any user logs on or just when the current user logs on? If you're doing something like having some code check for updates or ensure something is running in the user session, then I would suggest you create the task as part of your installation that will run with elevate permissions.  


Originally posted: 2016-03-28T09:42:27
