### ISSUE TITLE
Unhandled exceptions on history tab 

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#672]
Hi.  
Thanks for your work!  
  
I found two exceptions on history tab of edit dialog. May be they are low but both are unhandled.   
Steps to reproduce  
1.  

- open task edit dialog on existing task
- go to history tab and close dialog before loading is ended.

    &quot;Object reference not set to an instance of an object.&quot;
       at System.Windows.Forms.ListView.InsertItems(Int32 displayIndex, ListViewItem[] items, Boolean checkHosting)
       at System.Windows.Forms.ListView.ApplyUpdateCachedItems()
       at System.Windows.Forms.ListView.Sort()
       at System.Windows.Forms.ListView.ListViewNativeItemCollection.AddRange(ListViewItem[] values)
       at System.Windows.Forms.ListView.ListViewItemCollection.AddRange(ListViewItem[] items)
       at Microsoft.Win32.TaskScheduler.TaskHistoryControl.historyBackgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\spb.Common Components\TaskScheduler\TaskService\TaskEditor\TaskHistoryControl.cs:line 239

2.  

- open task edit dialog on existing task
- go to history tab
- try to sort any column  before loading is ended.

    &quot;Object reference not set to an instance of an object.&quot;
       at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)
       at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
       at System.Windows.Forms.ListView.WndProc(Message&amp; m)
       at System.Windows.Forms.ListViewEx.WndProc(Message&amp; m) in C:\spb.Common Components\TaskScheduler\TaskService\TaskEditor\Native\ListViewEx.cs:line 183

Originally posted: 2016-02-16T06:09:14

**Comment by dahall** [comment]
The second error I temporally suppressed by try|catch in ListViewEx.WndProc(ref Message m) .  
  
try{ base.WndProc(ref m); }catch {}  


Originally posted: 2016-02-16T06:20:48

**Comment by dahall** [comment]
Both are fixed in 2.5.15, due shortly. Thanks for the posts and detail.  


Originally posted: 2016-02-16T10:31:47

**Comment by dahall** [comment]
Thanks!  


Originally posted: 2016-02-17T07:59:52
