### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#731]
The current version of the native library (1.1) does not support the version of the &quot;(Task Name Goes Here)&quot; task (0.0)
    
    The exception occurred at Microsoft.Win32.TaskScheduler.Task.GetV2Definition(TaskService svc, IRegisteredTask iTask, Boolean throwError) in C:\Users\dahall\Documents\Visual Studio 2010\Projects\TaskService\Task.cs:line 1515
    at Microsoft.Win32.TaskScheduler.Task.get_Definition() in C:\Users\dahall\Documents\Visual Studio 2010\Projects\TaskService\Task.cs:line 850

My program made the task and saved the task, how can it not read it back?  

Originally posted: 2016-11-10T14:44:39

**Comment by dahall** [comment]
Will you supply the version of Windows on which this error occurred? Also, if possible, can you send me the XML of the created task? This is most securely done by sending me a personal message through this site.  


Originally posted: 2016-11-11T07:39:04

**Comment by dahall** [comment]
Windows 10 64-bit, unfortunately I don't have the XML data. Is there some way of getting the raw XML data from the exception object when such an exception occurs?  


Originally posted: 2016-11-17T19:43:58

**Comment by dahall** [comment]
Take the task you create and save, on any system, and collect the XML for it using the native "Task Scheduler" system applet. That will suffice. You cannot get it from the exception. That error is occurring because the wrapper cannot parse the XML in an expected format.  


Originally posted: 2016-11-18T08:24:55
