### ISSUE TITLE
FileNotFoundException in TaskService.GetTask(taskName);

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#79]
Hi!
 
it.s common practice for methods like GetTask(taskName); 
to return NULL when task wasn't found because it's expected value for situation when task is not available.
 
Thank's

Originally posted: 2009-09-23T09:17:17

**Comment by dahall** [comment]
var exisingTask = ts.GetTask(taskName);
                if (exisingTask != null)
                {
                    ts.RootFolder.DeleteTask(taskName);
                }

Originally posted: 2009-09-23T09:17:50

**Comment by dahall** [comment]
I also found this problem when I tried my application on Windows XP

Originally posted: 2009-09-23T18:33:22

**Comment by dahall** [comment]
This is the error: (as taskPath I used ---> @"\"+taskName <----   theTask = backupTaskService.GetTask(@"\"+nameOfTask);

No problems with Windows Vista/7

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Microsoft.Win32.TaskScheduler.V1Interop.ITaskScheduler.Activate(String Name, Guid& riid)
   at Microsoft.Win32.TaskScheduler.TaskService.GetTask(ITaskScheduler iSvc, String name)
   at Microsoft.Win32.TaskScheduler.TaskService.GetTask(String taskPath)
   at MailBrowserBackup.ScheduleClass.getTriggerProperties()
   at MailBrowserBackup.ScheduleWnd..ctor()
   at MailBrowserBackup.MainWnd.schedulerBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)



Originally posted: 2009-09-23T18:45:21

**Comment by dahall** [comment]
This issue only affected tasks under the V1 engine that are not found as named. An exception was thrown and not handled. Line 132 of TaskService.cs was modified to handle the exception so that GetTask will always return null if the specified task is not found.

Originally posted: 2009-09-29T21:14:05
