### ISSUE TITLE
TaskFolder.RegisterTaskDefinition throws exception in V1

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#80]
I am trying to update an existing task using the code below, this functions fine in Vista/7 but when i'm trying it out on XP it crashes citing that the file already exists. This makes sense but looking at the source code it should be trying to update the existing task instead trying to create a new one. Thanks for your assistance with this problem.
 
Unhandled Exception: System.Runtime.InteropServices.COMException (0x80070050): The file exists. (Exception from HRESULT: 0x80070050)
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at Microsoft.Win32.TaskScheduler.TaskDefinition.V1Save(String newName)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition)
   at LiquidScheduler.Program.Main(String[] args)
 
 
TaskService lqScheduler = new TaskService();
TaskDefinition lqTaskDefinition = lqScheduler.NewTask();
DailyTrigger lqTrigger = new DailyTrigger();
lqTrigger.DaysInterval = 1;
lqTrigger.StartBoundary = DateTime.Parse("2009-01-01T" + lqScheduleTime + ":00");
lqTaskDefinition.Triggers.Add(lqTrigger);
ExecAction lqAction = new ExecAction(Environment.CurrentDirectory+"\\Liquid.exe", lqScheduleRunCommand, Environment.CurrentDirectory);
lqTaskDefinition.Actions.Add(lqAction);                    
lqScheduler.RootFolder.RegisterTaskDefinition(lqTaskName, lqTaskDefinition);

Originally posted: 2009-10-06T05:40:56

**Comment by dahall** [comment]
The only time I have seen this exception is when the file is locked, hidden, or read-only. You can check this by looking in the \Windows\Tasks directory for a file with the name you are trying to use with a .job extension. Check the attributes. If all attributes are normal, please let me know. I have run this code on my test XP machine without problem using parameters I made up.

Originally posted: 2009-10-06T11:48:31

**Comment by dahall** [comment]
I think i've found the problem the task name I was trying to edit had a hyphen in it, removing that seems to work as expected.

Originally posted: 2009-10-07T03:22:30

**Comment by dahall** [comment]
User resolved issue by removing hyphen from name under V1.

Originally posted: 2010-02-08T12:00:54
