### ISSUE TITLE
COMException: Interface not registered (Exception from HRESULT: 0x80040155)

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#84]
Sample code:
 
implemented with Microsoft.Win32.Scheduler version 1.42
but also reproducible with latest trunk;
 
class TaskRepository {
 
private TaskService taskService;
private string taskPrefix = "MyTask";
 
public TaskRepository()
{
  taskService = new TaskService();
}
 
public void Save(Credentials credentials, string shellInstruction)
{
    if(credentials == null)
      throw new ArgumentNullException("credentials");
      
    if(string.IsNullOrEmpty(shellInstruction))
      throw new ArgumentNullException("shellInstruction");
 
    var taskDefenition = taskService.NewTask();
    taskDefenition.RegistrationInfo.Author = Strings.ApplicationName;
    taskDefenition.Settings.ExecutionTimeLimit = TimeSpan.FromHours(24);
    taskDefenition.Principal.RunLevel = Win32.TaskRunLevel.Highest;
    taskDefenition.Actions.Add(new Win32.ExecAction(mainAppPath, shellInstruction, null));
    
    taskService.RootFolder.RegisterTaskDefinition(
				taskPrefix + DateTime.Now.ToString("ddMMyyyyHHmmss"),
				taskDefenition,
				TaskCreation.CreateOrUpdate,
				credentials.Name,
				credentials.Password,
				TaskLogonType.Password, null);  
}
 
public IEnumerable<TaskDefinition> Load()
{
    var rootTasks = taskService.RootFolder.Tasks;
    List<TaskDefinition> result = new List<TaskDefinition>();
       
		foreach (var task in rootTasks)
		{
			if (task.Name.StartsWith(prefix, StringComparison.InvariantCultureIgnoreCase))
					result.Add(task.Definition); // task.Definition <--- Exception thrown here
		}				
		return result;
}
}
 
COMException: Interface not registered (Exception from HRESULT: 0x80040155)
at Microsoft.Win32.TaskScheduler.V2Interop.IRegisteredTask.get_Definition()
   at Microsoft.Win32.TaskScheduler.Task.get_Definition()
   at Scheduler.TaskRepository.Load() in ...\TaskRepository.cs:line 40
 
OS: Win7.
 
Tasks are created successfully, but while loading created tasks ComException is thrown on task.Definition property;

Originally posted: 2010-03-23T06:17:21

**Comment by dahall** [comment]
Do you have local administration rights on the pc causing the exception? I remember having problems with registering com interfaces with vista/7. Are you allowing the app through UAC and running as admin?

Originally posted: 2010-03-23T06:38:10

**Comment by dahall** [comment]
2 IIvanden:
Yes. I do have administrator rights. The application is started with Administrator permissions.
The exception is thrown when trying to access Definition property which is of type ITaskDefinition. Don't understand how this may happen when I just created Task from new TaskDefinition.

Originally posted: 2010-03-23T12:56:40

**Comment by dahall** [comment]
Will you provide the code or describe the properties you have set on the definition when you register it the first time?

Originally posted: 2010-03-24T00:30:22

**Comment by dahall** [comment]
Here you go

Originally posted: 2010-03-24T02:54:29

**Comment by dahall** [comment]
Hi,
I was loading Tasks in separate thread which probably has less privileges. This caused an exception.
Thanks. The issue can be closed;

Originally posted: 2010-03-26T02:31:19

**Comment by dahall** [comment]
This issue is happening again.
I've tested the latest version (2.5.21) on Windows 7 and 10.
I'm using a WinForm project with the UI thread using that lib (New TaskService().RootFolder) and then when listing the scheduled tasks from another thread it fails:

System.Runtime.InteropServices.COMException (0x80040155): Interface not registered (Exception from HRESULT: 0x80040155)
   at Microsoft.Win32.TaskScheduler.V2Interop.IRegisteredTask.get_Definition()
   at Microsoft.Win32.TaskScheduler.Task.GetV2Definition(TaskService svc, IRegisteredTask iTask, Boolean throwError)
   at Microsoft.Win32.TaskScheduler.Task.get_Definition()
...

Thank you for your help.
/Lio

Originally posted: 2016-09-21T10:56:42

**Comment by dahall** [comment]
The base Microsoft library is not thread safe and is in a COM Apartment Threaded model which assumes a single thread. Each class must be used only with other classes instantiated in the same thread, including, and most importantly, the TaskService class.

Originally posted: 2016-09-21T12:17:03

**Comment by dahall** [comment]
Tasks loaded in separate thread having less privileges. This caused an exception. Elevating thread privileges corrected issue.

Originally posted: 2010-03-27T17:24:39
