### ISSUE TITLE
taskscheduleditor System.NullReferenceException was unhandled on XP

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#86]
Is the editor supposed to work on XP? I got past the reference issue, tested on my win7 box, but on XP...
With the following code:
Const TaskName As String = "Test"
 
'play with task editor
Using ts As TaskService = New TaskService
'set up task
Dim TmTrigger As New TimeTrigger
TmTrigger.StartBoundary = DateTime.Now + TimeSpan.FromMinutes(1)
TmTrigger.Enabled = True
Dim Action As New ExecAction("notepad.exe", "c:\test.log", "c:\")
Dim t As Task
t = ts.AddTask(TaskName, TmTrigger, Action)
 
Dim EditorForm As New TaskEditDialog()
 
EditorForm.Editable = True
EditorForm.Initialize(t)
If EditorForm.ShowDialog = Windows.Forms.DialogResult.OK Then
ts.RootFolder.RegisterTaskDefinition(TaskName, EditorForm.TaskDefinition)
End If
End Using
 
on the "EditorForm.Initialize(t)" line I get the following exception.
 
System.NullReferenceException was unhandled
Message="Object reference not set to an instance of an object."
Source="Microsoft.Win32.TaskScheduler"
StackTrace:
at Microsoft.Win32.TaskScheduler.TaskService.ShouldSerializeUserName()
at Microsoft.Win32.TaskScheduler.TaskService.get_UserName()
at Microsoft.Win32.TaskScheduler.TaskPropertiesControl.set_TaskDefinition(TaskDefinition value)
at Microsoft.Win32.TaskScheduler.TaskPropertiesControl.set_Task(Task value)
at Microsoft.Win32.TaskScheduler.TaskPropertiesControl.Initialize(Task task)
at Microsoft.Win32.TaskScheduler.TaskEditDialog.Initialize(Task task)
at taskschedplay.Form1.btnCreate_Click(Object sender, EventArgs e) in C:\Visual Studio Projects\ben\taskschedplay\taskschedplay\Form1.vb:line 45
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(ApplicationContext context)
at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
at taskschedplay.My.MyApplication.Main(String[] Args) in 17d14f5c-a337-4978-8281-53493378c1071.vb:line 81
at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
 
At first I thought it was because I was using vs2005, so I installed on a fresh virtual XP box vs2008 express, I get the same error.
 
I figured it was better to create a new issue than change the reason for the old one.

Originally posted: 2010-06-07T08:34:58

**Comment by dahall** [comment]
Corrected in code drop 52599.

Originally posted: 2010-06-15T11:30:35
