### ISSUE TITLE
Task.GetRunTimes throws AccessViolationException

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#87]
I cannot retrieve the scheduled run times for an existing (and enabled) task through Task.GetRunTimes. If the date range is small enough so that no run times should be returned, I successfully get an empty DateTime array back. But in case that there are run times, I get the AccessViolationException below. I'm on Windows 7 64-bit.
 
System.AccessViolationException was unhandled
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=mscorlib
  StackTrace:
       at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
       at Microsoft.Win32.TaskScheduler.Task.GetRunTimes(DateTime start, DateTime end)

Originally posted: 2010-06-27T07:51:01

**Comment by dahall** [comment]
Fixed in source code drop 54024 for both V1 and V2.

Originally posted: 2010-07-01T16:22:21
