### ISSUE TITLE
Missing WeeklyTrigger constructor

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#93]
************** Exception Text **************
System.MissingMethodException: Method not found: 'Void Microsoft.Win32.TaskScheduler.WeeklyTrigger..ctor()'.
   at System.ComponentModel.ReflectPropertyDescriptor.SetValue(Object component, Object value)
   at System.Windows.Forms.RadioButton.PerformAutoUpdates(Boolean tabbedInto)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at Microsoft.Win32.TaskScheduler.TriggerEditDialog.set_Trigger(Trigger value)
   at Microsoft.Win32.TaskScheduler.TriggerEditDialog..ctor(Trigger trigger, Boolean supportV1Only)
   at Microsoft.Win32.TaskScheduler.TaskPropertiesControl.triggerEditButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 
 
Windows 7, C#, latest code version. To reproduce:
Create programmatically DailyTrigger for a new task and call TaskEditDialog for this task. The exception above is shown when you try edit the Daily trigger. The same exception is shown when you add a new trigger on the same screen and try to change to Daily or Weekly. You can bypass the exception but the trigger stays the One Time one.

Originally posted: 2010-11-24T17:14:47

**Comment by dahall** [comment]
I am unable to reproduce this. Can you send me the code that you have used to create the error?

Originally posted: 2010-11-24T22:43:19

**Comment by dahall** [comment]
First, file versions, just in case:
Microsoft.Win32.TaskScheduler.dll - 10/26/2010
Microsoft.Win32.TaskSchedulerEditor.dll - 7/4/2010

The code is:
		TaskService ts = new TaskService();

		TaskDefinition td = ts.NewTask();
		td.RegistrationInfo.Description = m_TaskName;

		td.Actions.Add(new ExecAction(m_AppName, m_Parameter, m_Dir));

		// Register the task in the ADSC folder
		TaskFolder ADSFolder = FolderExist(ts.RootFolder, "ADSC");
		if (ADSFolder == null)
			ADSFolder = ts.RootFolder.CreateFolder("\\ADSC");
		ADSFolder.RegisterTaskDefinition(m_TaskName, td);

		// Retrieve the task, change the trigger and re-register it
		Task t = ADSFolder.Tasks[m_TaskName];
		td = t.Definition;
		DailyTrigger dTrigger = (DailyTrigger)td.Triggers.Add(new DailyTrigger(1));
		dTrigger.StartBoundary = DateTime.Today;
		dTrigger.EndBoundary = DateTime.Today + TimeSpan.FromDays(36500);// Hundred years is enough :-)
		ADSFolder.RegisterTaskDefinition(m_TaskName, td);

		// Offer to edit task for time etc.
		t = ADSFolder.Tasks[m_TaskName];
		// Edit task and re-register if user clicks Ok
		TaskEditDialog editorForm = new TaskEditDialog();
		editorForm.Editable = true;
		editorForm.Initialize(t);
		if (editorForm.ShowDialog() == System.Windows.Forms.DialogResult.OK)
			ADSFolder.RegisterTaskDefinition(taskName, editorForm.TaskDefinition);

Originally posted: 2010-11-26T08:06:35

**Comment by dahall** [comment]
BTW, if there is a workaround, I'd gladly take it :-)

Originally posted: 2010-11-26T16:30:04

**Comment by dahall** [comment]
Will you try your code against the assemblies in the attached file? They are the most recent builds from the checked in source. Let me know if you have the problem. I am not able to reproduce it. Also, let me know if you are using Visual Studio 2010.

Originally posted: 2010-11-27T15:34:48

**Comment by dahall** [comment]
Hi Dahall,

Thanks for your efforts. I'll try your code Monday. For now just telling that I use VS 2008 for C# and use my code with your library in COM environment called from an old-fashioned C++.

-Anna

Originally posted: 2010-11-27T20:11:01

**Comment by dahall** [comment]
Hi Dahall,

Whatever were the changes for the last build they did the trick: no error :-). Thanks!

-Anna

Originally posted: 2010-11-29T08:43:45

**Comment by dahall** [comment]
David,

I assume that the source code available for the download corresponds to the latest dll's that you have suggested me to try. Is that correct?

-Anna

Originally posted: 2010-11-29T09:02:11

**Comment by dahall** [comment]
One more question: which Visual Studio do you use to build your code?

Originally posted: 2010-11-29T09:25:51

**Comment by dahall** [comment]
These assemblies are from a build of the last source code upload. I use Visual Studio 2010 to do the builds. I need to do some further testing of the changes to the editor before releasing this build but you should be able to use it as there will not be any major changes. Glad this worked for you.

Originally posted: 2010-11-29T13:45:32

**Comment by dahall** [comment]
Fixed with source code release 60274.

Originally posted: 2010-11-29T13:46:59
